### ISSUE TITLE
Нужен CORS доступ для экспериментов по админке

### ISSUE THREAD

**Issue by NtsDK** [gurkalov/eva-position#2]
Нужен CORS доступ для экспериментов по админке. От меня что-то нужно для этого?

**Comment by gurkalov** [comment]
@NtsDK думаю поставить * пока на все)

**Comment by gurkalov** [comment]
@NtsDK 

```
fetch('http://94.103.85.103');
fetch('http://position.evarun.ru');
```
Проверяй!

**Comment by NtsDK** [comment]
@gurkalov 
Попробовал. Пока не очень.

```
const url = "http://position.evarun.ru";
const path = '/api/v1/login';
fetch(url + path, {
	"method": "post",
	"mode": "cors",
	"headers": {
		"content-type": "application/json",
	},
	body: JSON.stringify({
	  "email": "???",
	  "password": "???"
	})
}).then(console.log).catch(console.error);
```

Говорит

![image](https://user-images.githubusercontent.com/669689/54960407-c576e600-4f5c-11e9-9b77-8f74cf4c87ce.png)

**Comment by gurkalov** [comment]
@NtsDK Попробуй сейчас

**Comment by NtsDK** [comment]
@gurkalov 
Ошибка немного изменилась
![image](https://user-images.githubusercontent.com/669689/55032710-cae23800-5011-11e9-93b1-96dd812513c3.png)

**Comment by gurkalov** [comment]
@NtsDK а креды правильные не пробовал подставлять?

Для экспериментов можно и no-cors mode попробовать. Но я вчера успешно авторизовывался с localhost.

**Comment by gurkalov** [comment]
Done
