### ISSUE TITLE
Сделать веб-доступ к редактированию списка маяков в табличном виде

### ISSUE THREAD

**Issue by Artyrm** [gurkalov/eva-position#3]
Сошлись на том, что проще всего эту задачу решает PHPMyAdmin.

Договорились, что вечером сегодня реально сделать.

**Comment by Artyrm** [comment]
Чо-как?

**Comment by gurkalov** [comment]
@Artyrm 
http://85.143.222.113:27777
Креды в телеграме.

**Comment by gurkalov** [comment]
Актуальный адрес PHPMyAdmin
http://85.143.222.113:27777
